/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SemAcessoRouteImport } from './routes/sem-acesso'
import { Route as AuthenticatedAfiliadosRouteImport } from './routes/_authenticated/afiliados'
import { Route as AuthenticatedColetoresRouteImport } from './routes/_authenticated/coletores'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCuponsRouteImport } from './routes/_authenticated/cupons'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLojasRouteImport } from './routes/_authenticated/lojas'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedTelegramRouteImport } from './routes/_authenticated/telegram'
import { Route as AuthenticatedWorkersRouteImport } from './routes/_authenticated/workers'
import { Route as AuthenticatedOfertasOfferIdRouteImport } from './routes/_authenticated/ofertas.$offerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SemAcessoRoute = SemAcessoRouteImport.update({
  id: '/sem-acesso',
  path: '/sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAfiliadosRoute = AuthenticatedAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColetoresRoute = AuthenticatedColetoresRouteImport.update({
  id: '/coletores',
  path: '/coletores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCuponsRoute = AuthenticatedCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojasRoute = AuthenticatedLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTelegramRoute = AuthenticatedTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfertasOfferIdRoute =
  AuthenticatedOfertasOfferIdRouteImport.update({
    id: '/$offerId',
    path: '/$offerId',
    getParentRoute: () => AuthenticatedOfertasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/coletores': typeof AuthenticatedColetoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cupons': typeof AuthenticatedCuponsRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/ofertas': typeof AuthenticatedOfertasRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/telegram': typeof AuthenticatedTelegramRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/ofertas/$offerId': typeof AuthenticatedOfertasOfferIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/coletores': typeof AuthenticatedColetoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cupons': typeof AuthenticatedCuponsRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/ofertas': typeof AuthenticatedOfertasRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/telegram': typeof AuthenticatedTelegramRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/ofertas/$offerId': typeof AuthenticatedOfertasOfferIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/_authenticated/afiliados': typeof AuthenticatedAfiliadosRoute
  '/_authenticated/coletores': typeof AuthenticatedColetoresRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cupons': typeof AuthenticatedCuponsRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/lojas': typeof AuthenticatedLojasRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRouteWithChildren
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/telegram': typeof AuthenticatedTelegramRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
  '/_authenticated/ofertas/$offerId': typeof AuthenticatedOfertasOfferIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sem-acesso'
    | '/afiliados'
    | '/coletores'
    | '/configuracoes'
    | '/cupons'
    | '/historico'
    | '/logs'
    | '/lojas'
    | '/ofertas'
    | '/painel'
    | '/produtos'
    | '/telegram'
    | '/workers'
    | '/ofertas/$offerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sem-acesso'
    | '/afiliados'
    | '/coletores'
    | '/configuracoes'
    | '/cupons'
    | '/historico'
    | '/logs'
    | '/lojas'
    | '/ofertas'
    | '/painel'
    | '/produtos'
    | '/telegram'
    | '/workers'
    | '/ofertas/$offerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sem-acesso'
    | '/_authenticated/afiliados'
    | '/_authenticated/coletores'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cupons'
    | '/_authenticated/historico'
    | '/_authenticated/logs'
    | '/_authenticated/lojas'
    | '/_authenticated/ofertas'
    | '/_authenticated/painel'
    | '/_authenticated/produtos'
    | '/_authenticated/telegram'
    | '/_authenticated/workers'
    | '/_authenticated/ofertas/$offerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SemAcessoRoute: typeof SemAcessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-acesso': {
      id: '/sem-acesso'
      path: '/sem-acesso'
      fullPath: '/sem-acesso'
      preLoaderRoute: typeof SemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/afiliados': {
      id: '/_authenticated/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AuthenticatedAfiliadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coletores': {
      id: '/_authenticated/coletores'
      path: '/coletores'
      fullPath: '/coletores'
      preLoaderRoute: typeof AuthenticatedColetoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cupons': {
      id: '/_authenticated/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof AuthenticatedCuponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojas': {
      id: '/_authenticated/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AuthenticatedLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telegram': {
      id: '/_authenticated/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AuthenticatedTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ofertas/$offerId': {
      id: '/_authenticated/ofertas/$offerId'
      path: '/$offerId'
      fullPath: '/ofertas/$offerId'
      preLoaderRoute: typeof AuthenticatedOfertasOfferIdRouteImport
      parentRoute: typeof AuthenticatedOfertasRoute
    }
  }
}

interface AuthenticatedOfertasRouteChildren {
  AuthenticatedOfertasOfferIdRoute: typeof AuthenticatedOfertasOfferIdRoute
}

const AuthenticatedOfertasRouteChildren: AuthenticatedOfertasRouteChildren = {
  AuthenticatedOfertasOfferIdRoute: AuthenticatedOfertasOfferIdRoute,
}

const AuthenticatedOfertasRouteWithChildren =
  AuthenticatedOfertasRoute._addFileChildren(AuthenticatedOfertasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAfiliadosRoute: typeof AuthenticatedAfiliadosRoute
  AuthenticatedColetoresRoute: typeof AuthenticatedColetoresRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCuponsRoute: typeof AuthenticatedCuponsRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedLojasRoute: typeof AuthenticatedLojasRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRouteWithChildren
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedTelegramRoute: typeof AuthenticatedTelegramRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAfiliadosRoute: AuthenticatedAfiliadosRoute,
  AuthenticatedColetoresRoute: AuthenticatedColetoresRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCuponsRoute: AuthenticatedCuponsRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedLojasRoute: AuthenticatedLojasRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRouteWithChildren,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedTelegramRoute: AuthenticatedTelegramRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SemAcessoRoute: SemAcessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}